# environment.yml

name: DataMining
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - contourpy=1.3.0=py39h2b77a98_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - double-conversion=3.3.1=he0c23c2_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.59.1=py39h5769e4c_0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=11.0.0=h9e37d49_0
  - icu=75.1=he0c23c2_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - kiwisolver=1.4.7=py39h2b77a98_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.11.0=2_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=2_h2a3cdd5_mkl
  - libclang13=21.1.6=default_ha2db4b5_0
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_14
  - libglib=2.84.0=h7025463_0
  - libgomp=15.2.0=h8ee18e1_14
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=2_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libpng=1.6.51=h7351971_0
  - libsqlite=3.51.1=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.6=h4fa8253_0
  - matplotlib=3.9.4=py39hcbf5309_0
  - matplotlib-base=3.9.4=py39h5376392_0
  - mkl=2025.3.0=hac47afa_454
  - munkres=1.1.4=pyhd8ed1ab_1
  - networkx=3.2.1=pyhd8ed1ab_0
  - numpy=2.0.2=py39h60232e0_1
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.44=h99c9b8b_2
  - pillow=11.3.0=py39hbad85af_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - pthread-stubs=0.4=h0e40799_1002
  - pyparsing=3.2.3=pyhe01879c_2
  - pyside6=6.9.0=py39h5cc861e_0
  - python=3.9.23=h8c5b53a_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.9=8_cp39
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.0=h83cda92_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.13=h2c6b04d_3
  - tornado=6.5.2=py39h0802e32_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=16.0.0=py39ha55e580_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.12.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - datasets==4.4.2
      - datasketch==1.8.0
      - dill==0.4.0
      - exceptiongroup==1.3.1
      - filelock==3.19.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hdbscan==0.8.40
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - llvmlite==0.43.0
      - markupsafe==3.0.3
      - mmh3==5.2.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - numba==0.60.0
      - outcome==1.3.0.post0
      - pandas==2.3.3
      - propcache==0.4.1
      - pyarrow==21.0.0
      - pycparser==2.23
      - pynndescent==0.5.13
      - pysocks==1.7.1
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - selenium==4.36.0
      - sentence-transformers==5.1.2
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.8.0
      - tqdm==4.67.1
      - transformers==4.57.3
      - trio==0.31.0
      - trio-websocket==0.12.2
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - webdriver-manager==4.0.2
      - websocket-client==1.9.0
      - wsproto==1.2.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: D:\Anaconda\envs\DataMining
